#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

# Do not build on tags (GitHub and BitBucket)
skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\build-tool

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: false     # set this flag to immediately finish build once one of the jobs fails.

install:
  - nuget restore

cache:
  - packages -> **\packages.config

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: build-tool.sln         # path to Visual Studio solution or project
